global:
  scrape_interval: 5s
  scrape_timeout: 1s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'main_receiver:3002'
          - 'first_consumer:3001'
